### ISSUE TITLE
Inputs from existing apps

### ISSUE THREAD

**Issue by katdivyareddy10** [Project-Unknown-2020/puzzle-hustle#2]
1. Swapnee
2. ImGenius
3. Jigsaw Puzzle Epic
4. Jigsaw Puzzle world

**Comment by gouthamreddy09** [comment]
animations are really good in the swapnee app. from devs view i feel its really imp to focus on animations.

**Comment by katdivyareddy10** [comment]
I like their categories display but we can do it as a vertical list instead of a horizontal one.

**Comment by katdivyareddy10** [comment]
@sunilvootkur, @ericmin409 any other thoughts from sample apps?

**Comment by katdivyareddy10** [comment]
@sunilvootkur  add the cool apps that you talked about to the main description!

**Comment by katdivyareddy10** [comment]
Most stuff is implemented using Swapnee as reference.
