### ISSUE TITLE
Check pricing options

### ISSUE THREAD

**Issue by katdivyareddy10** [Project-Unknown-2020/puzzle-hustle#3]
Check pricing options for server hosting for 
- AWS
- Heroku
- Google Cloud 
- Azure 
- Like services

**Comment by katdivyareddy10** [comment]
@sunilvootkur @ericmin409 - Can you two look up pricing options?

**Comment by ericmin409** [comment]
https://www.reddit.com/r/gamedev/comments/8hbmu6/cost_of_the_game_servers/
https://www.reddit.com/r/gamedev/comments/8qv6zk/best_options_for_server_hosting/

I'm seeing suggestions about focusing on P2P hosting for first time game devs. I also saw other recommended server options if we do want to get one like Linode, Digitalocean and Vultr  which start as low as $1/month and have options in the $10-100/mo range and higher as well.

**Comment by katdivyareddy10** [comment]
Went with Heroku finally!
