### ISSUE TITLE
Sample images 

### ISSUE THREAD

**Issue by katdivyareddy10** [Project-Unknown-2020/puzzle-hustle#4]
Get sample images for the project from 10 different categories. 
- Images should be `SQUARE`
- Up to 10 images in each category

Example sites:
- [Anime](https://www.zerochan.net/1%3A1+Ratio)
- [Category Specific ](https://unsplash.com/s/photos/images?orientation=squarish)

**Comment by ericmin409** [comment]
Added 10 images to the img library. Wasn't sure if I was supposed to put them somewhere else

**Comment by katdivyareddy10** [comment]
All images are added to categoryimages.js file
